Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = "2023.3.0"

  [["kali", "192.168.56.10"]].each do |machineName, ipAddr|
    config.vm.define "#{machineName}" do |i|
      i.vm.network "private_network", ip: "#{ipAddr}"
      i.vm.hostname = "#{machineName}"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
